env=Environment()

def Wget(target,url_prefix):
  return env.Command(target,[],'wget {}/{}'.format(url_prefix,target))
def Targz(target,source):
  return env.Command(target,source,'tar zxvf {}'.format(source))

c = Wget('helm-v2.14.3-linux-amd64.tar.gz','https://get.helm.sh')

c = Targz('linux-amd64/helm','helm-v2.14.3-linux-amd64.tar.gz')
Clean(c,'linux-amd64/')

c = env.Install('/usr/local/bin','linux-amd64/helm')

#Default('/usr/local/bin/helm')

