import os
import string
import random

def random_string(length):
    return ''.join(random.choice(string.ascii_letters) for m in xrange(length))

env=Environment()

env['ENV']['PATH'] = ':'.join([env['ENV']['PATH'],
                              '/sbin','/usr/local/go/bin'])
env['ENV']['HOME'] = os.environ['HOME']

def install_cluster():
    cluster=os.environ.get('MANAGEMENT_CLUSTER','M-{}'.format(random_string(4)))
    outdir='./out/{}'.format(cluster)
    manifest='{}/cluster.yaml'.format(outdir)
    cfg='{}/kubeconfig'.format(outdir)

    c = env.Command(cfg,manifest,'./create_management_cluster.sh {}'.format(cluster))
    c = env.Command(manifest,[],'./generate_manifests.sh {}'.format(cluster))
    Clean(c,outdir)
    env.Alias('management-cluster',cfg)

install_cluster()
env.Default('management-cluster')
